// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "douyin.proto" (package "douyin", syntax proto3)
// tslint:disable

/**
 * @generated from protobuf message douyin.Response
 */
export interface Response {
    /**
     * @generated from protobuf field: repeated douyin.Message messagesList = 1;
     */
    messagesList: Message[];
    /**
     * @generated from protobuf field: string cursor = 2;
     */
    cursor: string;
    /**
     * @generated from protobuf field: uint64 fetchInterval = 3;
     */
    fetchInterval: bigint;
    /**
     * @generated from protobuf field: uint64 now = 4;
     */
    now: bigint;
    /**
     * @generated from protobuf field: string internalExt = 5;
     */
    internalExt: string;
    /**
     * @generated from protobuf field: uint32 fetchType = 6;
     */
    fetchType: number;
    /**
     * @generated from protobuf field: map<string, string> routeParams = 7;
     */
    routeParams: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: uint64 heartbeatDuration = 8;
     */
    heartbeatDuration: bigint;
    /**
     * @generated from protobuf field: bool needAck = 9;
     */
    needAck: boolean;
    /**
     * @generated from protobuf field: string pushServer = 10;
     */
    pushServer: string;
    /**
     * @generated from protobuf field: string liveCursor = 11;
     */
    liveCursor: string;
    /**
     * @generated from protobuf field: bool historyNoMore = 12;
     */
    historyNoMore: boolean;
}
/**
 * @generated from protobuf message douyin.Message
 */
export interface Message {
    /**
     * @generated from protobuf field: string method = 1;
     */
    method: string;
    /**
     * @generated from protobuf field: bytes payload = 2;
     */
    payload: Uint8Array;
    /**
     * @generated from protobuf field: int64 msgId = 3;
     */
    msgId: bigint;
    /**
     * @generated from protobuf field: int32 msgType = 4;
     */
    msgType: number;
    /**
     * @generated from protobuf field: int64 offset = 5;
     */
    offset: bigint;
    /**
     * @generated from protobuf field: bool needWrdsStore = 6;
     */
    needWrdsStore: boolean;
    /**
     * @generated from protobuf field: int64 wrdsVersion = 7;
     */
    wrdsVersion: bigint;
    /**
     * @generated from protobuf field: string wrdsSubKey = 8;
     */
    wrdsSubKey: string;
}
/**
 * @generated from protobuf message douyin.EmojiChatMessage
 */
export interface EmojiChatMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: int64 emojiId = 3;
     */
    emojiId: bigint;
    /**
     * @generated from protobuf field: douyin.Text emojiContent = 4;
     */
    emojiContent?: Text;
    /**
     * @generated from protobuf field: string defaultContent = 5;
     */
    defaultContent: string;
    /**
     * @generated from protobuf field: douyin.Image backgroundImage = 6;
     */
    backgroundImage?: Image;
    /**
     * @generated from protobuf field: bool fromIntercom = 7;
     */
    fromIntercom: boolean;
    /**
     * @generated from protobuf field: bool intercomHideUserCard = 8;
     */
    intercomHideUserCard: boolean;
}
/**
 * 聊天
 *
 * @generated from protobuf message douyin.ChatMessage
 */
export interface ChatMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: string content = 3;
     */
    content: string;
    /**
     * @generated from protobuf field: bool visibleToSender = 4;
     */
    visibleToSender: boolean;
    /**
     * @generated from protobuf field: douyin.Image backgroundImage = 5;
     */
    backgroundImage?: Image;
    /**
     * @generated from protobuf field: string fullScreenTextColor = 6;
     */
    fullScreenTextColor: string;
    /**
     * @generated from protobuf field: douyin.Image backgroundImageV2 = 7;
     */
    backgroundImageV2?: Image;
    /**
     * @generated from protobuf field: douyin.PublicAreaCommon publicAreaCommon = 9;
     */
    publicAreaCommon?: PublicAreaCommon;
    /**
     * @generated from protobuf field: douyin.Image giftImage = 10;
     */
    giftImage?: Image;
    /**
     * @generated from protobuf field: uint64 agreeMsgId = 11;
     */
    agreeMsgId: bigint;
    /**
     * @generated from protobuf field: uint32 priorityLevel = 12;
     */
    priorityLevel: number;
    /**
     * @generated from protobuf field: douyin.LandscapeAreaCommon landscapeAreaCommon = 13;
     */
    landscapeAreaCommon?: LandscapeAreaCommon;
    /**
     * @generated from protobuf field: uint64 eventTime = 15;
     */
    eventTime: bigint;
    /**
     * @generated from protobuf field: bool sendReview = 16;
     */
    sendReview: boolean;
    /**
     * @generated from protobuf field: bool fromIntercom = 17;
     */
    fromIntercom: boolean;
    /**
     * @generated from protobuf field: bool intercomHideUserCard = 18;
     */
    intercomHideUserCard: boolean;
    /**
     *  repeated chatTagsList = 19;
     *
     * @generated from protobuf field: string chatBy = 20;
     */
    chatBy: string;
    /**
     * @generated from protobuf field: uint32 individualChatPriority = 21;
     */
    individualChatPriority: number;
    /**
     * @generated from protobuf field: douyin.Text rtfContent = 22;
     */
    rtfContent?: Text;
}
/**
 * @generated from protobuf message douyin.LandscapeAreaCommon
 */
export interface LandscapeAreaCommon {
    /**
     * @generated from protobuf field: bool showHead = 1;
     */
    showHead: boolean;
    /**
     * @generated from protobuf field: bool showNickname = 2;
     */
    showNickname: boolean;
    /**
     * @generated from protobuf field: bool showFontColor = 3;
     */
    showFontColor: boolean;
    /**
     * @generated from protobuf field: repeated string colorValueList = 4;
     */
    colorValueList: string[];
    /**
     * @generated from protobuf field: repeated douyin.CommentTypeTag commentTypeTagsList = 5;
     */
    commentTypeTagsList: CommentTypeTag[];
}
/**
 * @generated from protobuf message douyin.RoomUserSeqMessage
 */
export interface RoomUserSeqMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: repeated douyin.RoomUserSeqMessageContributor ranksList = 2;
     */
    ranksList: RoomUserSeqMessageContributor[];
    /**
     * @generated from protobuf field: int64 total = 3;
     */
    total: bigint;
    /**
     * @generated from protobuf field: string popStr = 4;
     */
    popStr: string;
    /**
     * @generated from protobuf field: repeated douyin.RoomUserSeqMessageContributor seatsList = 5;
     */
    seatsList: RoomUserSeqMessageContributor[];
    /**
     * @generated from protobuf field: int64 popularity = 6;
     */
    popularity: bigint;
    /**
     * @generated from protobuf field: int64 totalUser = 7;
     */
    totalUser: bigint;
    /**
     * @generated from protobuf field: string totalUserStr = 8;
     */
    totalUserStr: string;
    /**
     * @generated from protobuf field: string totalStr = 9;
     */
    totalStr: string;
    /**
     * @generated from protobuf field: string onlineUserForAnchor = 10;
     */
    onlineUserForAnchor: string;
    /**
     * @generated from protobuf field: string totalPvForAnchor = 11;
     */
    totalPvForAnchor: string;
    /**
     * @generated from protobuf field: string upRightStatsStr = 12;
     */
    upRightStatsStr: string;
    /**
     * @generated from protobuf field: string upRightStatsStrComplete = 13;
     */
    upRightStatsStrComplete: string;
}
/**
 * @generated from protobuf message douyin.CommonTextMessage
 */
export interface CommonTextMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: string scene = 3;
     */
    scene: string;
}
/**
 * @generated from protobuf message douyin.UpdateFanTicketMessage
 */
export interface UpdateFanTicketMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: string roomFanTicketCountText = 2;
     */
    roomFanTicketCountText: string;
    /**
     * @generated from protobuf field: uint64 roomFanTicketCount = 3;
     */
    roomFanTicketCount: bigint;
    /**
     * @generated from protobuf field: bool forceUpdate = 4;
     */
    forceUpdate: boolean;
}
/**
 * @generated from protobuf message douyin.RoomUserSeqMessageContributor
 */
export interface RoomUserSeqMessageContributor {
    /**
     * @generated from protobuf field: uint64 score = 1;
     */
    score: bigint;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: uint64 rank = 3;
     */
    rank: bigint;
    /**
     * @generated from protobuf field: uint64 delta = 4;
     */
    delta: bigint;
    /**
     * @generated from protobuf field: bool isHidden = 5;
     */
    isHidden: boolean;
    /**
     * @generated from protobuf field: string scoreDescription = 6;
     */
    scoreDescription: string;
    /**
     * @generated from protobuf field: string exactlyScore = 7;
     */
    exactlyScore: string;
}
/**
 * 礼物消息
 *
 * @generated from protobuf message douyin.GiftMessage
 */
export interface GiftMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: uint64 giftId = 2;
     */
    giftId: bigint;
    /**
     * @generated from protobuf field: uint64 fanTicketCount = 3;
     */
    fanTicketCount: bigint;
    /**
     * @generated from protobuf field: uint64 groupCount = 4;
     */
    groupCount: bigint;
    /**
     * @generated from protobuf field: uint64 repeatCount = 5;
     */
    repeatCount: bigint;
    /**
     * @generated from protobuf field: uint64 comboCount = 6;
     */
    comboCount: bigint;
    /**
     * @generated from protobuf field: douyin.User user = 7;
     */
    user?: User;
    /**
     * @generated from protobuf field: douyin.User toUser = 8;
     */
    toUser?: User;
    /**
     * @generated from protobuf field: uint32 repeatEnd = 9;
     */
    repeatEnd: number;
    /**
     * @generated from protobuf field: douyin.TextEffect textEffect = 10;
     */
    textEffect?: TextEffect;
    /**
     * @generated from protobuf field: uint64 groupId = 11;
     */
    groupId: bigint;
    /**
     * @generated from protobuf field: uint64 incomeTaskgifts = 12;
     */
    incomeTaskgifts: bigint;
    /**
     * @generated from protobuf field: uint64 roomFanTicketCount = 13;
     */
    roomFanTicketCount: bigint;
    /**
     * @generated from protobuf field: douyin.GiftIMPriority priority = 14;
     */
    priority?: GiftIMPriority;
    /**
     * @generated from protobuf field: douyin.GiftStruct gift = 15;
     */
    gift?: GiftStruct;
    /**
     * @generated from protobuf field: string logId = 16;
     */
    logId: string;
    /**
     * @generated from protobuf field: uint64 sendType = 17;
     */
    sendType: bigint;
    /**
     * @generated from protobuf field: douyin.PublicAreaCommon publicAreaCommon = 18;
     */
    publicAreaCommon?: PublicAreaCommon;
    /**
     * @generated from protobuf field: douyin.Text trayDisplayText = 19;
     */
    trayDisplayText?: Text;
    /**
     * @generated from protobuf field: uint64 bannedDisplayEffects = 20;
     */
    bannedDisplayEffects: bigint;
    /**
     *  GiftTrayInfo trayInfo = 21;
     *  AssetEffectMixInfo assetEffectMixInfo = 22;
     *
     * @generated from protobuf field: bool displayForSelf = 25;
     */
    displayForSelf: boolean;
    /**
     * @generated from protobuf field: string interactGiftInfo = 26;
     */
    interactGiftInfo: string;
    /**
     * @generated from protobuf field: string diyItemInfo = 27;
     */
    diyItemInfo: string;
    /**
     * @generated from protobuf field: repeated uint64 minAssetSetList = 28;
     */
    minAssetSetList: bigint[];
    /**
     * @generated from protobuf field: uint64 totalCount = 29;
     */
    totalCount: bigint;
    /**
     * @generated from protobuf field: uint32 clientGiftSource = 30;
     */
    clientGiftSource: number;
    /**
     *  AnchorGiftData anchorGift = 31;
     *
     * @generated from protobuf field: repeated uint64 toUserIdsList = 32;
     */
    toUserIdsList: bigint[];
    /**
     * @generated from protobuf field: uint64 sendTime = 33;
     */
    sendTime: bigint;
    /**
     * @generated from protobuf field: uint64 forceDisplayEffects = 34;
     */
    forceDisplayEffects: bigint;
    /**
     * @generated from protobuf field: string traceId = 35;
     */
    traceId: string;
    /**
     * @generated from protobuf field: uint64 effectDisplayTs = 36;
     */
    effectDisplayTs: bigint;
}
/**
 * @generated from protobuf message douyin.GiftStruct
 */
export interface GiftStruct {
    /**
     * @generated from protobuf field: douyin.Image image = 1;
     */
    image?: Image;
    /**
     * @generated from protobuf field: string describe = 2;
     */
    describe: string;
    /**
     * @generated from protobuf field: bool notify = 3;
     */
    notify: boolean;
    /**
     * @generated from protobuf field: uint64 duration = 4;
     */
    duration: bigint;
    /**
     * @generated from protobuf field: uint64 id = 5;
     */
    id: bigint;
    /**
     *  GiftStructFansClubInfo fansclubInfo = 6;
     *
     * @generated from protobuf field: bool forLinkmic = 7;
     */
    forLinkmic: boolean;
    /**
     * @generated from protobuf field: bool doodle = 8;
     */
    doodle: boolean;
    /**
     * @generated from protobuf field: bool forFansclub = 9;
     */
    forFansclub: boolean;
    /**
     * @generated from protobuf field: bool combo = 10;
     */
    combo: boolean;
    /**
     * @generated from protobuf field: uint32 type = 11;
     */
    type: number;
    /**
     * @generated from protobuf field: uint32 diamondCount = 12;
     */
    diamondCount: number;
    /**
     * @generated from protobuf field: bool isDisplayedOnPanel = 13;
     */
    isDisplayedOnPanel: boolean;
    /**
     * @generated from protobuf field: uint64 primaryEffectId = 14;
     */
    primaryEffectId: bigint;
    /**
     * @generated from protobuf field: douyin.Image giftLabelIcon = 15;
     */
    giftLabelIcon?: Image;
    /**
     * @generated from protobuf field: string name = 16;
     */
    name: string;
    /**
     * @generated from protobuf field: string region = 17;
     */
    region: string;
    /**
     * @generated from protobuf field: string manual = 18;
     */
    manual: string;
    /**
     * @generated from protobuf field: bool forCustom = 19;
     */
    forCustom: boolean;
    /**
     *  specialEffectsMap = 20;
     *
     * @generated from protobuf field: douyin.Image icon = 21;
     */
    icon?: Image;
    /**
     * @generated from protobuf field: uint32 actionType = 22;
     */
    actionType: number; // fixme 后面的就不写了还有几十个属性
}
/**
 * @generated from protobuf message douyin.GiftIMPriority
 */
export interface GiftIMPriority {
    /**
     * @generated from protobuf field: repeated uint64 queueSizesList = 1;
     */
    queueSizesList: bigint[];
    /**
     * @generated from protobuf field: uint64 selfQueuePriority = 2;
     */
    selfQueuePriority: bigint;
    /**
     * @generated from protobuf field: uint64 priority = 3;
     */
    priority: bigint;
}
/**
 * @generated from protobuf message douyin.TextEffect
 */
export interface TextEffect {
    /**
     * @generated from protobuf field: douyin.TextEffectDetail portrait = 1;
     */
    portrait?: TextEffectDetail;
    /**
     * @generated from protobuf field: douyin.TextEffectDetail landscape = 2;
     */
    landscape?: TextEffectDetail;
}
/**
 * @generated from protobuf message douyin.TextEffectDetail
 */
export interface TextEffectDetail {
    /**
     * @generated from protobuf field: douyin.Text text = 1;
     */
    text?: Text;
    /**
     * @generated from protobuf field: uint32 textFontSize = 2;
     */
    textFontSize: number;
    /**
     * @generated from protobuf field: douyin.Image background = 3;
     */
    background?: Image;
    /**
     * @generated from protobuf field: uint32 start = 4;
     */
    start: number;
    /**
     * @generated from protobuf field: uint32 duration = 5;
     */
    duration: number;
    /**
     * @generated from protobuf field: uint32 x = 6;
     */
    x: number;
    /**
     * @generated from protobuf field: uint32 y = 7;
     */
    y: number;
    /**
     * @generated from protobuf field: uint32 width = 8;
     */
    width: number;
    /**
     * @generated from protobuf field: uint32 height = 9;
     */
    height: number;
    /**
     * @generated from protobuf field: uint32 shadowDx = 10;
     */
    shadowDx: number;
    /**
     * @generated from protobuf field: uint32 shadowDy = 11;
     */
    shadowDy: number;
    /**
     * @generated from protobuf field: uint32 shadowRadius = 12;
     */
    shadowRadius: number;
    /**
     * @generated from protobuf field: string shadowColor = 13;
     */
    shadowColor: string;
    /**
     * @generated from protobuf field: string strokeColor = 14;
     */
    strokeColor: string;
    /**
     * @generated from protobuf field: uint32 strokeWidth = 15;
     */
    strokeWidth: number;
}
/**
 * 成员消息
 *
 * @generated from protobuf message douyin.MemberMessage
 */
export interface MemberMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: uint64 memberCount = 3;
     */
    memberCount: bigint;
    /**
     * @generated from protobuf field: douyin.User operator = 4;
     */
    operator?: User;
    /**
     * @generated from protobuf field: bool isSetToAdmin = 5;
     */
    isSetToAdmin: boolean;
    /**
     * @generated from protobuf field: bool isTopUser = 6;
     */
    isTopUser: boolean;
    /**
     * @generated from protobuf field: uint64 rankScore = 7;
     */
    rankScore: bigint;
    /**
     * @generated from protobuf field: uint64 topUserNo = 8;
     */
    topUserNo: bigint;
    /**
     * @generated from protobuf field: uint64 enterType = 9;
     */
    enterType: bigint;
    /**
     * @generated from protobuf field: uint64 action = 10;
     */
    action: bigint;
    /**
     * @generated from protobuf field: string actionDescription = 11;
     */
    actionDescription: string;
    /**
     * @generated from protobuf field: uint64 userId = 12;
     */
    userId: bigint;
    /**
     * @generated from protobuf field: douyin.EffectConfig effectConfig = 13;
     */
    effectConfig?: EffectConfig;
    /**
     * @generated from protobuf field: string popStr = 14;
     */
    popStr: string;
    /**
     * @generated from protobuf field: douyin.EffectConfig enterEffectConfig = 15;
     */
    enterEffectConfig?: EffectConfig;
    /**
     * @generated from protobuf field: douyin.Image backgroundImage = 16;
     */
    backgroundImage?: Image;
    /**
     * @generated from protobuf field: douyin.Image backgroundImageV2 = 17;
     */
    backgroundImageV2?: Image;
    /**
     * @generated from protobuf field: douyin.Text anchorDisplayText = 18;
     */
    anchorDisplayText?: Text;
    /**
     * @generated from protobuf field: douyin.PublicAreaCommon publicAreaCommon = 19;
     */
    publicAreaCommon?: PublicAreaCommon;
    /**
     * @generated from protobuf field: uint64 userEnterTipType = 20;
     */
    userEnterTipType: bigint;
    /**
     * @generated from protobuf field: uint64 anchorEnterTipType = 21;
     */
    anchorEnterTipType: bigint;
}
/**
 * @generated from protobuf message douyin.PublicAreaCommon
 */
export interface PublicAreaCommon {
    /**
     * @generated from protobuf field: douyin.Image userLabel = 1;
     */
    userLabel?: Image;
    /**
     * @generated from protobuf field: uint64 userConsumeInRoom = 2;
     */
    userConsumeInRoom: bigint;
    /**
     * @generated from protobuf field: uint64 userSendGiftCntInRoom = 3;
     */
    userSendGiftCntInRoom: bigint;
}
/**
 * @generated from protobuf message douyin.EffectConfig
 */
export interface EffectConfig {
    /**
     * @generated from protobuf field: uint64 type = 1;
     */
    type: bigint;
    /**
     * @generated from protobuf field: douyin.Image icon = 2;
     */
    icon?: Image;
    /**
     * @generated from protobuf field: uint64 avatarPos = 3;
     */
    avatarPos: bigint;
    /**
     * @generated from protobuf field: douyin.Text text = 4;
     */
    text?: Text;
    /**
     * @generated from protobuf field: douyin.Image textIcon = 5;
     */
    textIcon?: Image;
    /**
     * @generated from protobuf field: uint32 stayTime = 6;
     */
    stayTime: number;
    /**
     * @generated from protobuf field: uint64 animAssetId = 7;
     */
    animAssetId: bigint;
    /**
     * @generated from protobuf field: douyin.Image badge = 8;
     */
    badge?: Image;
    /**
     * @generated from protobuf field: repeated uint64 flexSettingArrayList = 9;
     */
    flexSettingArrayList: bigint[];
    /**
     * @generated from protobuf field: douyin.Image textIconOverlay = 10;
     */
    textIconOverlay?: Image;
    /**
     * @generated from protobuf field: douyin.Image animatedBadge = 11;
     */
    animatedBadge?: Image;
    /**
     * @generated from protobuf field: bool hasSweepLight = 12;
     */
    hasSweepLight: boolean;
    /**
     * @generated from protobuf field: repeated uint64 textFlexSettingArrayList = 13;
     */
    textFlexSettingArrayList: bigint[];
    /**
     * @generated from protobuf field: uint64 centerAnimAssetId = 14;
     */
    centerAnimAssetId: bigint;
    /**
     * @generated from protobuf field: douyin.Image dynamicImage = 15;
     */
    dynamicImage?: Image;
    /**
     * @generated from protobuf field: map<string, string> extraMap = 16;
     */
    extraMap: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: uint64 mp4AnimAssetId = 17;
     */
    mp4AnimAssetId: bigint;
    /**
     * @generated from protobuf field: uint64 priority = 18;
     */
    priority: bigint;
    /**
     * @generated from protobuf field: uint64 maxWaitTime = 19;
     */
    maxWaitTime: bigint;
    /**
     * @generated from protobuf field: string dressId = 20;
     */
    dressId: string;
    /**
     * @generated from protobuf field: uint64 alignment = 21;
     */
    alignment: bigint;
    /**
     * @generated from protobuf field: uint64 alignmentOffset = 22;
     */
    alignmentOffset: bigint;
}
/**
 * @generated from protobuf message douyin.Text
 */
export interface Text {
    /**
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * @generated from protobuf field: string defaultPatter = 2;
     */
    defaultPatter: string;
    /**
     * @generated from protobuf field: douyin.TextFormat defaultFormat = 3;
     */
    defaultFormat?: TextFormat;
    /**
     * @generated from protobuf field: repeated douyin.TextPiece piecesList = 4;
     */
    piecesList: TextPiece[];
}
/**
 * @generated from protobuf message douyin.TextPiece
 */
export interface TextPiece {
    /**
     * @generated from protobuf field: bool type = 1;
     */
    type: boolean;
    /**
     * @generated from protobuf field: douyin.TextFormat format = 2;
     */
    format?: TextFormat;
    /**
     * @generated from protobuf field: string stringValue = 3;
     */
    stringValue: string;
    /**
     * @generated from protobuf field: douyin.TextPieceUser userValue = 4;
     */
    userValue?: TextPieceUser;
    /**
     * @generated from protobuf field: douyin.TextPieceGift giftValue = 5;
     */
    giftValue?: TextPieceGift;
    /**
     * @generated from protobuf field: douyin.TextPieceHeart heartValue = 6;
     */
    heartValue?: TextPieceHeart;
    /**
     * @generated from protobuf field: douyin.TextPiecePatternRef patternRefValue = 7;
     */
    patternRefValue?: TextPiecePatternRef;
    /**
     * @generated from protobuf field: douyin.TextPieceImage imageValue = 8;
     */
    imageValue?: TextPieceImage;
}
/**
 * @generated from protobuf message douyin.TextPieceImage
 */
export interface TextPieceImage {
    /**
     * @generated from protobuf field: douyin.Image image = 1;
     */
    image?: Image;
    /**
     * @generated from protobuf field: float scalingRate = 2;
     */
    scalingRate: number;
}
/**
 * @generated from protobuf message douyin.TextPiecePatternRef
 */
export interface TextPiecePatternRef {
    /**
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * @generated from protobuf field: string defaultPattern = 2;
     */
    defaultPattern: string;
}
/**
 * @generated from protobuf message douyin.TextPieceHeart
 */
export interface TextPieceHeart {
    /**
     * @generated from protobuf field: string color = 1;
     */
    color: string;
}
/**
 * @generated from protobuf message douyin.TextPieceGift
 */
export interface TextPieceGift {
    /**
     * @generated from protobuf field: uint64 giftId = 1;
     */
    giftId: bigint;
    /**
     * @generated from protobuf field: douyin.PatternRef nameRef = 2;
     */
    nameRef?: PatternRef;
}
/**
 * @generated from protobuf message douyin.PatternRef
 */
export interface PatternRef {
    /**
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * @generated from protobuf field: string defaultPattern = 2;
     */
    defaultPattern: string;
}
/**
 * @generated from protobuf message douyin.TextPieceUser
 */
export interface TextPieceUser {
    /**
     * @generated from protobuf field: douyin.User user = 1;
     */
    user?: User;
    /**
     * @generated from protobuf field: bool withColon = 2;
     */
    withColon: boolean;
}
/**
 * @generated from protobuf message douyin.TextFormat
 */
export interface TextFormat {
    /**
     * @generated from protobuf field: string color = 1;
     */
    color: string;
    /**
     * @generated from protobuf field: bool bold = 2;
     */
    bold: boolean;
    /**
     * @generated from protobuf field: bool italic = 3;
     */
    italic: boolean;
    /**
     * @generated from protobuf field: uint32 weight = 4;
     */
    weight: number;
    /**
     * @generated from protobuf field: uint32 italicAngle = 5;
     */
    italicAngle: number;
    /**
     * @generated from protobuf field: uint32 fontSize = 6;
     */
    fontSize: number;
    /**
     * @generated from protobuf field: bool useHeighLightColor = 7;
     */
    useHeighLightColor: boolean;
    /**
     * @generated from protobuf field: bool useRemoteClor = 8;
     */
    useRemoteClor: boolean;
}
/**
 * 点赞
 *
 * @generated from protobuf message douyin.LikeMessage
 */
export interface LikeMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: uint64 count = 2;
     */
    count: bigint;
    /**
     * @generated from protobuf field: uint64 total = 3;
     */
    total: bigint;
    /**
     * @generated from protobuf field: uint64 color = 4;
     */
    color: bigint;
    /**
     * @generated from protobuf field: douyin.User user = 5;
     */
    user?: User;
    /**
     * @generated from protobuf field: string icon = 6;
     */
    icon: string;
    /**
     * @generated from protobuf field: douyin.DoubleLikeDetail doubleLikeDetail = 7;
     */
    doubleLikeDetail?: DoubleLikeDetail;
    /**
     * @generated from protobuf field: douyin.DisplayControlInfo displayControlInfo = 8;
     */
    displayControlInfo?: DisplayControlInfo;
    /**
     * @generated from protobuf field: uint64 linkmicGuestUid = 9;
     */
    linkmicGuestUid: bigint;
    /**
     * @generated from protobuf field: string scene = 10;
     */
    scene: string;
    /**
     * @generated from protobuf field: douyin.PicoDisplayInfo picoDisplayInfo = 11;
     */
    picoDisplayInfo?: PicoDisplayInfo;
}
/**
 * @generated from protobuf message douyin.SocialMessage
 */
export interface SocialMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: uint64 shareType = 3;
     */
    shareType: bigint;
    /**
     * @generated from protobuf field: uint64 action = 4;
     */
    action: bigint;
    /**
     * @generated from protobuf field: string shareTarget = 5;
     */
    shareTarget: string;
    /**
     * @generated from protobuf field: uint64 followCount = 6;
     */
    followCount: bigint;
    /**
     * @generated from protobuf field: douyin.PublicAreaCommon publicAreaCommon = 7;
     */
    publicAreaCommon?: PublicAreaCommon;
}
/**
 * @generated from protobuf message douyin.PicoDisplayInfo
 */
export interface PicoDisplayInfo {
    /**
     * @generated from protobuf field: uint64 comboSumCount = 1;
     */
    comboSumCount: bigint;
    /**
     * @generated from protobuf field: string emoji = 2;
     */
    emoji: string;
    /**
     * @generated from protobuf field: douyin.Image emojiIcon = 3;
     */
    emojiIcon?: Image;
    /**
     * @generated from protobuf field: string emojiText = 4;
     */
    emojiText: string;
}
/**
 * @generated from protobuf message douyin.DoubleLikeDetail
 */
export interface DoubleLikeDetail {
    /**
     * @generated from protobuf field: bool doubleFlag = 1;
     */
    doubleFlag: boolean;
    /**
     * @generated from protobuf field: uint32 seqId = 2;
     */
    seqId: number;
    /**
     * @generated from protobuf field: uint32 renewalsNum = 3;
     */
    renewalsNum: number;
    /**
     * @generated from protobuf field: uint32 triggersNum = 4;
     */
    triggersNum: number;
}
/**
 * @generated from protobuf message douyin.DisplayControlInfo
 */
export interface DisplayControlInfo {
    /**
     * @generated from protobuf field: bool showText = 1;
     */
    showText: boolean;
    /**
     * @generated from protobuf field: bool showIcons = 2;
     */
    showIcons: boolean;
}
/**
 * @generated from protobuf message douyin.EpisodeChatMessage
 */
export interface EpisodeChatMessage {
    /**
     * @generated from protobuf field: douyin.Message common = 1;
     */
    common?: Message;
    /**
     * @generated from protobuf field: douyin.User user = 2;
     */
    user?: User;
    /**
     * @generated from protobuf field: string content = 3;
     */
    content: string;
    /**
     * @generated from protobuf field: bool visibleToSende = 4;
     */
    visibleToSende: boolean;
    /**
     *   BackgroundImage backgroundImage = 5;
     *   PublicAreaCommon publicAreaCommon = 6;
     *
     * @generated from protobuf field: douyin.Image giftImage = 7;
     */
    giftImage?: Image;
    /**
     * @generated from protobuf field: uint64 agreeMsgId = 8;
     */
    agreeMsgId: bigint;
    /**
     * @generated from protobuf field: repeated string colorValueList = 9;
     */
    colorValueList: string[];
}
/**
 * @generated from protobuf message douyin.MatchAgainstScoreMessage
 */
export interface MatchAgainstScoreMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: douyin.Against against = 2;
     */
    against?: Against;
    /**
     * @generated from protobuf field: uint32 matchStatus = 3;
     */
    matchStatus: number;
    /**
     * @generated from protobuf field: uint32 displayStatus = 4;
     */
    displayStatus: number;
}
/**
 * @generated from protobuf message douyin.Against
 */
export interface Against {
    /**
     * @generated from protobuf field: string leftName = 1;
     */
    leftName: string;
    /**
     * @generated from protobuf field: douyin.Image leftLogo = 2;
     */
    leftLogo?: Image;
    /**
     * @generated from protobuf field: string leftGoal = 3;
     */
    leftGoal: string;
    /**
     *  LeftPlayersList leftPlayersList = 4;
     *  LeftGoalStageDetail leftGoalStageDetail = 5;
     *
     * @generated from protobuf field: string rightName = 6;
     */
    rightName: string;
    /**
     * @generated from protobuf field: douyin.Image rightLogo = 7;
     */
    rightLogo?: Image;
    /**
     * @generated from protobuf field: string rightGoal = 8;
     */
    rightGoal: string;
    /**
     *  RightPlayersList rightPlayersList  = 9;
     *  RightGoalStageDetail rightGoalStageDetail = 10;
     *
     * @generated from protobuf field: uint64 timestamp = 11;
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: uint64 version = 12;
     */
    version: bigint;
    /**
     * @generated from protobuf field: uint64 leftTeamId = 13;
     */
    leftTeamId: bigint;
    /**
     * @generated from protobuf field: uint64 rightTeamId = 14;
     */
    rightTeamId: bigint;
    /**
     * @generated from protobuf field: uint64 diffSei2absSecond = 15 [json_name = "diffSei2absSecond"];
     */
    diffSei2AbsSecond: bigint;
    /**
     * @generated from protobuf field: uint32 finalGoalStage = 16;
     */
    finalGoalStage: number;
    /**
     * @generated from protobuf field: uint32 currentGoalStage = 17;
     */
    currentGoalStage: number;
    /**
     * @generated from protobuf field: uint32 leftScoreAddition = 18;
     */
    leftScoreAddition: number;
    /**
     * @generated from protobuf field: uint32 rightScoreAddition = 19;
     */
    rightScoreAddition: number;
    /**
     * @generated from protobuf field: uint64 leftGoalInt = 20;
     */
    leftGoalInt: bigint;
    /**
     * @generated from protobuf field: uint64 rightGoalInt = 21;
     */
    rightGoalInt: bigint;
}
/**
 * @generated from protobuf message douyin.Common
 */
export interface Common {
    /**
     * @generated from protobuf field: string method = 1;
     */
    method: string;
    /**
     * @generated from protobuf field: uint64 msgId = 2;
     */
    msgId: bigint;
    /**
     * @generated from protobuf field: uint64 roomId = 3;
     */
    roomId: bigint;
    /**
     * @generated from protobuf field: uint64 createTime = 4;
     */
    createTime: bigint;
    /**
     * @generated from protobuf field: uint32 monitor = 5;
     */
    monitor: number;
    /**
     * @generated from protobuf field: bool isShowMsg = 6;
     */
    isShowMsg: boolean;
    /**
     * @generated from protobuf field: string describe = 7;
     */
    describe: string;
    /**
     *  DisplayText displayText = 8;
     *
     * @generated from protobuf field: uint64 foldType = 9;
     */
    foldType: bigint;
    /**
     * @generated from protobuf field: uint64 anchorFoldType = 10;
     */
    anchorFoldType: bigint;
    /**
     * @generated from protobuf field: uint64 priorityScore = 11;
     */
    priorityScore: bigint;
    /**
     * @generated from protobuf field: string logId = 12;
     */
    logId: string;
    /**
     * @generated from protobuf field: string msgProcessFilterK = 13;
     */
    msgProcessFilterK: string;
    /**
     * @generated from protobuf field: string msgProcessFilterV = 14;
     */
    msgProcessFilterV: string;
    /**
     * @generated from protobuf field: douyin.User user = 15;
     */
    user?: User;
    /**
     *  Room room = 16;
     *
     * @generated from protobuf field: uint64 anchorFoldTypeV2 = 17;
     */
    anchorFoldTypeV2: bigint;
    /**
     * @generated from protobuf field: uint64 processAtSeiTimeMs = 18;
     */
    processAtSeiTimeMs: bigint;
    /**
     * @generated from protobuf field: uint64 randomDispatchMs = 19;
     */
    randomDispatchMs: bigint;
    /**
     * @generated from protobuf field: bool isDispatch = 20;
     */
    isDispatch: boolean;
    /**
     * @generated from protobuf field: uint64 channelId = 21;
     */
    channelId: bigint;
    /**
     * @generated from protobuf field: uint64 diffSei2absSecond = 22 [json_name = "diffSei2absSecond"];
     */
    diffSei2AbsSecond: bigint;
    /**
     * @generated from protobuf field: uint64 anchorFoldDuration = 23;
     */
    anchorFoldDuration: bigint;
}
/**
 * @generated from protobuf message douyin.User
 */
export interface User {
    /**
     * @generated from protobuf field: uint64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: uint64 shortId = 2;
     */
    shortId: bigint;
    /**
     * @generated from protobuf field: string nickName = 3;
     */
    nickName: string;
    /**
     * @generated from protobuf field: uint32 gender = 4;
     */
    gender: number;
    /**
     * @generated from protobuf field: string Signature = 5 [json_name = "Signature"];
     */
    signature: string;
    /**
     * @generated from protobuf field: uint32 Level = 6 [json_name = "Level"];
     */
    level: number;
    /**
     * @generated from protobuf field: uint64 Birthday = 7 [json_name = "Birthday"];
     */
    birthday: bigint;
    /**
     * @generated from protobuf field: string Telephone = 8 [json_name = "Telephone"];
     */
    telephone: string;
    /**
     * @generated from protobuf field: douyin.Image AvatarThumb = 9 [json_name = "AvatarThumb"];
     */
    avatarThumb?: Image;
    /**
     * @generated from protobuf field: douyin.Image AvatarMedium = 10 [json_name = "AvatarMedium"];
     */
    avatarMedium?: Image;
    /**
     * @generated from protobuf field: douyin.Image AvatarLarge = 11 [json_name = "AvatarLarge"];
     */
    avatarLarge?: Image;
    /**
     * @generated from protobuf field: bool Verified = 12 [json_name = "Verified"];
     */
    verified: boolean;
    /**
     * @generated from protobuf field: uint32 Experience = 13 [json_name = "Experience"];
     */
    experience: number;
    /**
     * @generated from protobuf field: string city = 14;
     */
    city: string;
    /**
     * @generated from protobuf field: int32 Status = 15 [json_name = "Status"];
     */
    status: number;
    /**
     * @generated from protobuf field: uint64 CreateTime = 16 [json_name = "CreateTime"];
     */
    createTime: bigint;
    /**
     * @generated from protobuf field: uint64 ModifyTime = 17 [json_name = "ModifyTime"];
     */
    modifyTime: bigint;
    /**
     * @generated from protobuf field: uint32 Secret = 18 [json_name = "Secret"];
     */
    secret: number;
    /**
     * @generated from protobuf field: string ShareQrcodeUri = 19 [json_name = "ShareQrcodeUri"];
     */
    shareQrcodeUri: string;
    /**
     * @generated from protobuf field: uint32 IncomeSharePercent = 20 [json_name = "IncomeSharePercent"];
     */
    incomeSharePercent: number;
    /**
     * @generated from protobuf field: repeated douyin.Image BadgeImageList = 21 [json_name = "BadgeImageList"];
     */
    badgeImageList: Image[];
    /**
     * @generated from protobuf field: douyin.FollowInfo FollowInfo = 22 [json_name = "FollowInfo"];
     */
    followInfo?: FollowInfo;
    /**
     * @generated from protobuf field: douyin.PayGrade PayGrade = 23 [json_name = "PayGrade"];
     */
    payGrade?: PayGrade;
    /**
     * @generated from protobuf field: douyin.FansClub FansClub = 24 [json_name = "FansClub"];
     */
    fansClub?: FansClub;
    /**
     *  Border Border = 25;
     *
     * @generated from protobuf field: string SpecialId = 26 [json_name = "SpecialId"];
     */
    specialId: string;
    /**
     * @generated from protobuf field: douyin.Image AvatarBorder = 27 [json_name = "AvatarBorder"];
     */
    avatarBorder?: Image;
    /**
     * @generated from protobuf field: douyin.Image Medal = 28 [json_name = "Medal"];
     */
    medal?: Image;
    /**
     * @generated from protobuf field: repeated douyin.Image RealTimeIconsList = 29 [json_name = "RealTimeIconsList"];
     */
    realTimeIconsList: Image[];
    /**
     * @generated from protobuf field: string displayId = 38;
     */
    displayId: string;
    /**
     * @generated from protobuf field: string secUid = 46;
     */
    secUid: string;
    /**
     * @generated from protobuf field: uint64 fanTicketCount = 1022;
     */
    fanTicketCount: bigint;
    /**
     * @generated from protobuf field: string idStr = 1028;
     */
    idStr: string;
    /**
     * @generated from protobuf field: uint32 ageRange = 1045;
     */
    ageRange: number;
}
/**
 * @generated from protobuf message douyin.PayGrade
 */
export interface PayGrade {
    /**
     * @generated from protobuf field: int64 totalDiamondCount = 1;
     */
    totalDiamondCount: bigint;
    /**
     * @generated from protobuf field: douyin.Image diamondIcon = 2;
     */
    diamondIcon?: Image;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: douyin.Image icon = 4;
     */
    icon?: Image;
    /**
     * @generated from protobuf field: string nextName = 5;
     */
    nextName: string;
    /**
     * @generated from protobuf field: int64 level = 6;
     */
    level: bigint;
    /**
     * @generated from protobuf field: douyin.Image nextIcon = 7;
     */
    nextIcon?: Image;
    /**
     * @generated from protobuf field: int64 nextDiamond = 8;
     */
    nextDiamond: bigint;
    /**
     * @generated from protobuf field: int64 nowDiamond = 9;
     */
    nowDiamond: bigint;
    /**
     * @generated from protobuf field: int64 thisGradeMinDiamond = 10;
     */
    thisGradeMinDiamond: bigint;
    /**
     * @generated from protobuf field: int64 thisGradeMaxDiamond = 11;
     */
    thisGradeMaxDiamond: bigint;
    /**
     * @generated from protobuf field: int64 payDiamondBak = 12;
     */
    payDiamondBak: bigint;
    /**
     * @generated from protobuf field: string gradeDescribe = 13;
     */
    gradeDescribe: string;
    /**
     * @generated from protobuf field: repeated douyin.GradeIcon gradeIconList = 14;
     */
    gradeIconList: GradeIcon[];
    /**
     * @generated from protobuf field: int64 screenChatType = 15;
     */
    screenChatType: bigint;
    /**
     * @generated from protobuf field: douyin.Image imIcon = 16;
     */
    imIcon?: Image;
    /**
     * @generated from protobuf field: douyin.Image imIconWithLevel = 17;
     */
    imIconWithLevel?: Image;
    /**
     * @generated from protobuf field: douyin.Image liveIcon = 18;
     */
    liveIcon?: Image;
    /**
     * @generated from protobuf field: douyin.Image newImIconWithLevel = 19;
     */
    newImIconWithLevel?: Image;
    /**
     * @generated from protobuf field: douyin.Image newLiveIcon = 20;
     */
    newLiveIcon?: Image;
    /**
     * @generated from protobuf field: int64 upgradeNeedConsume = 21;
     */
    upgradeNeedConsume: bigint;
    /**
     * @generated from protobuf field: string nextPrivileges = 22;
     */
    nextPrivileges: string;
    /**
     * @generated from protobuf field: douyin.Image background = 23;
     */
    background?: Image;
    /**
     * @generated from protobuf field: douyin.Image backgroundBack = 24;
     */
    backgroundBack?: Image;
    /**
     * @generated from protobuf field: int64 score = 25;
     */
    score: bigint;
    /**
     * @generated from protobuf field: douyin.GradeBuffInfo buffInfo = 26;
     */
    buffInfo?: GradeBuffInfo;
    /**
     * @generated from protobuf field: string gradeBanner = 1001;
     */
    gradeBanner: string;
    /**
     * @generated from protobuf field: douyin.Image profileDialogBg = 1002;
     */
    profileDialogBg?: Image;
    /**
     * @generated from protobuf field: douyin.Image profileDialogBgBack = 1003;
     */
    profileDialogBgBack?: Image;
}
/**
 * @generated from protobuf message douyin.FansClub
 */
export interface FansClub {
    /**
     * @generated from protobuf field: douyin.FansClubData data = 1;
     */
    data?: FansClubData;
    /**
     * @generated from protobuf field: map<int32, douyin.FansClubData> preferData = 2;
     */
    preferData: {
        [key: number]: FansClubData;
    };
}
/**
 * @generated from protobuf message douyin.FansClubData
 */
export interface FansClubData {
    /**
     * @generated from protobuf field: string clubName = 1;
     */
    clubName: string;
    /**
     * @generated from protobuf field: int32 level = 2;
     */
    level: number;
    /**
     * @generated from protobuf field: int32 userFansClubStatus = 3;
     */
    userFansClubStatus: number;
    /**
     * @generated from protobuf field: douyin.UserBadge badge = 4;
     */
    badge?: UserBadge;
    /**
     * @generated from protobuf field: repeated int64 availableGiftIds = 5;
     */
    availableGiftIds: bigint[];
    /**
     * @generated from protobuf field: int64 anchorId = 6;
     */
    anchorId: bigint;
}
/**
 * @generated from protobuf message douyin.UserBadge
 */
export interface UserBadge {
    /**
     * @generated from protobuf field: map<int32, douyin.Image> icons = 1;
     */
    icons: {
        [key: number]: Image;
    };
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
}
/**
 * @generated from protobuf message douyin.GradeBuffInfo
 */
export interface GradeBuffInfo {
}
/**
 * @generated from protobuf message douyin.Border
 */
export interface Border {
}
/**
 * @generated from protobuf message douyin.GradeIcon
 */
export interface GradeIcon {
    /**
     * @generated from protobuf field: douyin.Image icon = 1;
     */
    icon?: Image;
    /**
     * @generated from protobuf field: int64 iconDiamond = 2;
     */
    iconDiamond: bigint;
    /**
     * @generated from protobuf field: int64 level = 3;
     */
    level: bigint;
    /**
     * @generated from protobuf field: string levelStr = 4;
     */
    levelStr: string;
}
/**
 * @generated from protobuf message douyin.FollowInfo
 */
export interface FollowInfo {
    /**
     * @generated from protobuf field: uint64 followingCount = 1;
     */
    followingCount: bigint;
    /**
     * @generated from protobuf field: uint64 followerCount = 2;
     */
    followerCount: bigint;
    /**
     * @generated from protobuf field: uint64 followStatus = 3;
     */
    followStatus: bigint;
    /**
     * @generated from protobuf field: uint64 pushStatus = 4;
     */
    pushStatus: bigint;
    /**
     * @generated from protobuf field: string remarkName = 5;
     */
    remarkName: string;
    /**
     * @generated from protobuf field: string followerCountStr = 6;
     */
    followerCountStr: string;
    /**
     * @generated from protobuf field: string followingCountStr = 7;
     */
    followingCountStr: string;
}
/**
 * @generated from protobuf message douyin.Image
 */
export interface Image {
    /**
     * @generated from protobuf field: repeated string urlListList = 1;
     */
    urlListList: string[];
    /**
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
    /**
     * @generated from protobuf field: uint64 height = 3;
     */
    height: bigint;
    /**
     * @generated from protobuf field: uint64 width = 4;
     */
    width: bigint;
    /**
     * @generated from protobuf field: string avgColor = 5;
     */
    avgColor: string;
    /**
     * @generated from protobuf field: uint32 imageType = 6;
     */
    imageType: number;
    /**
     * @generated from protobuf field: string openWebUrl = 7;
     */
    openWebUrl: string;
    /**
     * @generated from protobuf field: douyin.ImageContent content = 8;
     */
    content?: ImageContent;
    /**
     * @generated from protobuf field: bool isAnimated = 9;
     */
    isAnimated: boolean;
    /**
     * @generated from protobuf field: douyin.NinePatchSetting FlexSettingList = 10 [json_name = "FlexSettingList"];
     */
    flexSettingList?: NinePatchSetting;
    /**
     * @generated from protobuf field: douyin.NinePatchSetting TextSettingList = 11 [json_name = "TextSettingList"];
     */
    textSettingList?: NinePatchSetting;
}
/**
 * @generated from protobuf message douyin.NinePatchSetting
 */
export interface NinePatchSetting {
    /**
     * @generated from protobuf field: repeated string settingListList = 1;
     */
    settingListList: string[];
}
/**
 * @generated from protobuf message douyin.ImageContent
 */
export interface ImageContent {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string fontColor = 2;
     */
    fontColor: string;
    /**
     * @generated from protobuf field: uint64 level = 3;
     */
    level: bigint;
    /**
     * @generated from protobuf field: string alternativeText = 4;
     */
    alternativeText: string;
}
/**
 * @generated from protobuf message douyin.PushFrame
 */
export interface PushFrame {
    /**
     * @generated from protobuf field: uint64 seqId = 1;
     */
    seqId: bigint;
    /**
     * @generated from protobuf field: uint64 logId = 2;
     */
    logId: bigint;
    /**
     * @generated from protobuf field: uint64 service = 3;
     */
    service: bigint;
    /**
     * @generated from protobuf field: uint64 method = 4;
     */
    method: bigint;
    /**
     * @generated from protobuf field: repeated douyin.HeadersList headersList = 5;
     */
    headersList: HeadersList[];
    /**
     * @generated from protobuf field: string payloadEncoding = 6;
     */
    payloadEncoding: string;
    /**
     * @generated from protobuf field: string payloadType = 7;
     */
    payloadType: string;
    /**
     * @generated from protobuf field: bytes payload = 8;
     */
    payload: Uint8Array;
}
/**
 * @generated from protobuf message douyin.kk
 */
export interface kk {
    /**
     * @generated from protobuf field: uint32 k = 14;
     */
    k: number;
}
/**
 * @generated from protobuf message douyin.SendMessageBody
 */
export interface SendMessageBody {
    /**
     * @generated from protobuf field: string conversationId = 1;
     */
    conversationId: string;
    /**
     * @generated from protobuf field: uint32 conversationType = 2;
     */
    conversationType: number;
    /**
     * @generated from protobuf field: uint64 conversationShortId = 3;
     */
    conversationShortId: bigint;
    /**
     * @generated from protobuf field: string content = 4;
     */
    content: string;
    /**
     * @generated from protobuf field: repeated douyin.ExtList ext = 5;
     */
    ext: ExtList[];
    /**
     * @generated from protobuf field: uint32 messageType = 6;
     */
    messageType: number;
    /**
     * @generated from protobuf field: string ticket = 7;
     */
    ticket: string;
    /**
     * @generated from protobuf field: string clientMessageId = 8;
     */
    clientMessageId: string;
}
/**
 * @generated from protobuf message douyin.ExtList
 */
export interface ExtList {
    /**
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * @generated from protobuf field: string value = 2;
     */
    value: string;
}
/**
 * @generated from protobuf message douyin.Rsp
 */
export interface Rsp {
    /**
     * @generated from protobuf field: int32 a = 1;
     */
    a: number;
    /**
     * @generated from protobuf field: int32 b = 2;
     */
    b: number;
    /**
     * @generated from protobuf field: int32 c = 3;
     */
    c: number;
    /**
     * @generated from protobuf field: string d = 4;
     */
    d: string;
    /**
     * @generated from protobuf field: int32 e = 5;
     */
    e: number;
    /**
     * @generated from protobuf field: douyin.Rsp.F f = 6;
     */
    f?: Rsp_F;
    /**
     * @generated from protobuf field: string g = 7;
     */
    g: string;
    /**
     * @generated from protobuf field: uint64 h = 10;
     */
    h: bigint;
    /**
     * @generated from protobuf field: uint64 i = 11;
     */
    i: bigint;
    /**
     * @generated from protobuf field: uint64 j = 13;
     */
    j: bigint;
}
/**
 * @generated from protobuf message douyin.Rsp.F
 */
export interface Rsp_F {
    /**
     * @generated from protobuf field: uint64 q1 = 1;
     */
    q1: bigint;
    /**
     * @generated from protobuf field: uint64 q3 = 3;
     */
    q3: bigint;
    /**
     * @generated from protobuf field: string q4 = 4;
     */
    q4: string;
    /**
     * @generated from protobuf field: uint64 q5 = 5;
     */
    q5: bigint;
}
/**
 * @generated from protobuf message douyin.PreMessage
 */
export interface PreMessage {
    /**
     * @generated from protobuf field: uint32 cmd = 1;
     */
    cmd: number;
    /**
     * @generated from protobuf field: uint32 sequenceId = 2;
     */
    sequenceId: number;
    /**
     * @generated from protobuf field: string sdkVersion = 3;
     */
    sdkVersion: string;
    /**
     * @generated from protobuf field: string token = 4;
     */
    token: string;
    /**
     * @generated from protobuf field: uint32 refer = 5;
     */
    refer: number;
    /**
     * @generated from protobuf field: uint32 inboxType = 6;
     */
    inboxType: number;
    /**
     * @generated from protobuf field: string buildNumber = 7;
     */
    buildNumber: string;
    /**
     * @generated from protobuf field: douyin.SendMessageBody sendMessageBody = 8;
     */
    sendMessageBody?: SendMessageBody;
    /**
     * 字段名待定
     *
     * @generated from protobuf field: string aa = 9;
     */
    aa: string;
    /**
     * @generated from protobuf field: string devicePlatform = 11;
     */
    devicePlatform: string;
    /**
     * @generated from protobuf field: repeated douyin.HeadersList headers = 15;
     */
    headers: HeadersList[];
    /**
     * @generated from protobuf field: uint32 authType = 18;
     */
    authType: number;
    /**
     * @generated from protobuf field: string biz = 21;
     */
    biz: string;
    /**
     * @generated from protobuf field: string access = 22;
     */
    access: string;
}
/**
 * @generated from protobuf message douyin.HeadersList
 */
export interface HeadersList {
    /**
     * @generated from protobuf field: string key = 1;
     */
    key: string;
    /**
     * @generated from protobuf field: string value = 2;
     */
    value: string;
}
/**
 * @generated from protobuf message douyin.LiveShoppingMessage
 */
export interface LiveShoppingMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: int32 msgType = 2;
     */
    msgType: number;
    /**
     * @generated from protobuf field: int64 promotionId = 4;
     */
    promotionId: bigint;
}
/**
 * @generated from protobuf message douyin.RoomStatsMessage
 */
export interface RoomStatsMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: string displayShort = 2;
     */
    displayShort: string;
    /**
     * @generated from protobuf field: string displayMiddle = 3;
     */
    displayMiddle: string;
    /**
     * @generated from protobuf field: string displayLong = 4;
     */
    displayLong: string;
    /**
     * @generated from protobuf field: int64 displayValue = 5;
     */
    displayValue: bigint;
    /**
     * @generated from protobuf field: int64 displayVersion = 6;
     */
    displayVersion: bigint;
    /**
     * @generated from protobuf field: bool incremental = 7;
     */
    incremental: boolean;
    /**
     * @generated from protobuf field: bool isHidden = 8;
     */
    isHidden: boolean;
    /**
     * @generated from protobuf field: int64 total = 9;
     */
    total: bigint;
    /**
     * @generated from protobuf field: int64 displayType = 10;
     */
    displayType: bigint;
}
/**
 * @generated from protobuf message douyin.ProductInfo
 */
export interface ProductInfo {
    /**
     * @generated from protobuf field: int64 promotionId = 1;
     */
    promotionId: bigint;
    /**
     * @generated from protobuf field: int32 index = 2;
     */
    index: number;
    /**
     * @generated from protobuf field: repeated int64 targetFlashUidsList = 3;
     */
    targetFlashUidsList: bigint[];
    /**
     * @generated from protobuf field: int64 explainType = 4;
     */
    explainType: bigint;
}
/**
 * @generated from protobuf message douyin.CategoryInfo
 */
export interface CategoryInfo {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated int64 promotionIdsList = 3;
     */
    promotionIdsList: bigint[];
    /**
     * @generated from protobuf field: string type = 4;
     */
    type: string;
    /**
     * @generated from protobuf field: string uniqueIndex = 5;
     */
    uniqueIndex: string;
}
/**
 * @generated from protobuf message douyin.ProductChangeMessage
 */
export interface ProductChangeMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: int64 updateTimestamp = 2;
     */
    updateTimestamp: bigint;
    /**
     * @generated from protobuf field: string updateToast = 3;
     */
    updateToast: string;
    /**
     * @generated from protobuf field: repeated douyin.ProductInfo updateProductInfoList = 4;
     */
    updateProductInfoList: ProductInfo[];
    /**
     * @generated from protobuf field: int64 total = 5;
     */
    total: bigint;
    /**
     * @generated from protobuf field: repeated douyin.CategoryInfo updateCategoryInfoList = 8;
     */
    updateCategoryInfoList: CategoryInfo[];
}
/**
 * from https://github.com/HaoDong108/DouyinBarrageGrab/blob/main/BarrageGrab/proto/message.proto
 * status = 3 下播
 *
 * @generated from protobuf message douyin.ControlMessage
 */
export interface ControlMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: int32 status = 2;
     */
    status: number;
}
/**
 * from https://github.com/HaoDong108/DouyinBarrageGrab/blob/main/BarrageGrab/proto/message.proto
 *
 * @generated from protobuf message douyin.FansclubMessage
 */
export interface FansclubMessage {
    /**
     * @generated from protobuf field: douyin.Common commonInfo = 1;
     */
    commonInfo?: Common;
    /**
     * 升级是1，加入是2
     *
     * @generated from protobuf field: int32 type = 2;
     */
    type: number;
    /**
     * @generated from protobuf field: string content = 3;
     */
    content: string;
    /**
     * @generated from protobuf field: douyin.User user = 4;
     */
    user?: User;
}
/**
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomRankMessage.proto
 * 直播间排行榜
 *
 * @generated from protobuf message douyin.RoomRankMessage
 */
export interface RoomRankMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: repeated douyin.RoomRankMessage.RoomRank ranksList = 2;
     */
    ranksList: RoomRankMessage_RoomRank[];
}
/**
 * @generated from protobuf message douyin.RoomRankMessage.RoomRank
 */
export interface RoomRankMessage_RoomRank {
    /**
     * @generated from protobuf field: douyin.User user = 1;
     */
    user?: User;
    /**
     * @generated from protobuf field: string scoreStr = 2;
     */
    scoreStr: string;
    /**
     * @generated from protobuf field: bool profileHidden = 3;
     */
    profileHidden: boolean;
}
/**
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomMessage.proto
 *
 * @generated from protobuf message douyin.RoomMessage
 */
export interface RoomMessage {
    /**
     * @generated from protobuf field: douyin.Common common = 1;
     */
    common?: Common;
    /**
     * @generated from protobuf field: string content = 2;
     */
    content: string;
    /**
     * @generated from protobuf field: bool supprotLandscape = 3;
     */
    supprotLandscape: boolean;
    /**
     * @generated from protobuf field: douyin.RoomMsgTypeEnum roommessagetype = 4;
     */
    roommessagetype: RoomMsgTypeEnum;
    /**
     * @generated from protobuf field: bool systemTopMsg = 5;
     */
    systemTopMsg: boolean;
    /**
     * @generated from protobuf field: bool forcedGuarantee = 6;
     */
    forcedGuarantee: boolean;
    /**
     * @generated from protobuf field: string bizScene = 20;
     */
    bizScene: string;
    /**
     * @generated from protobuf field: map<string, string> buriedPointMap = 30;
     */
    buriedPointMap: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf enum douyin.CommentTypeTag
 */
export enum CommentTypeTag {
    /**
     * @generated from protobuf enum value: COMMENTTYPETAGUNKNOWN = 0;
     */
    COMMENTTYPETAGUNKNOWN = 0,
    /**
     * @generated from protobuf enum value: COMMENTTYPETAGSTAR = 1;
     */
    COMMENTTYPETAGSTAR = 1
}
/**
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomMsgTypeEnum.proto
 *
 * @generated from protobuf enum douyin.RoomMsgTypeEnum
 */
export enum RoomMsgTypeEnum {
    /**
     * @generated from protobuf enum value: DEFAULTROOMMSG = 0;
     */
    DEFAULTROOMMSG = 0,
    /**
     * @generated from protobuf enum value: ECOMLIVEREPLAYSAVEROOMMSG = 1;
     */
    ECOMLIVEREPLAYSAVEROOMMSG = 1,
    /**
     * @generated from protobuf enum value: CONSUMERRELATIONROOMMSG = 2;
     */
    CONSUMERRELATIONROOMMSG = 2,
    /**
     * @generated from protobuf enum value: JUMANJIDATAAUTHNOTIFYMSG = 3;
     */
    JUMANJIDATAAUTHNOTIFYMSG = 3,
    /**
     * @generated from protobuf enum value: VSWELCOMEMSG = 4;
     */
    VSWELCOMEMSG = 4,
    /**
     * @generated from protobuf enum value: MINORREFUNDMSG = 5;
     */
    MINORREFUNDMSG = 5,
    /**
     * @generated from protobuf enum value: PAIDLIVEROOMNOTIFYANCHORMSG = 6;
     */
    PAIDLIVEROOMNOTIFYANCHORMSG = 6,
    /**
     * @generated from protobuf enum value: HOSTTEAMSYSTEMMSG = 7;
     */
    HOSTTEAMSYSTEMMSG = 7
}
